// components/icons.tsx
import {
    AlertCircle,
    Battery,
    Calendar,
    Check,
    Edit,
    Plus,
    Settings,
    Phone,
    Hospital,
    Watch,
    Stethoscope,
    Activity,
    Droplet,
    Weight,
    Shield,
    Zap,
    BadgeCheck,
    Mail,
    MessageSquare,
    Users,
    Database,
    Send,
    Star,
    Grid3x3,
    Link,
    Unlink,
    Plug,
    AppWindow,
    Sparkles,
    CircleDashed,
    Key,
    Sliders,
    Microscope,
    ShieldCheck,
    TrendingUp,
    TrendingDown,
    Minus,
    LineChart, HeartPulse, Briefcase, Play, ArrowRight,
    Lock, Network, CloudSun, Building2, Pill, Wind, Flower2, Cloudy, Quote, BrainCircuit,
} from "lucide-react";

export const Icons = {
    alert: AlertCircle,
    battery: Battery,
    calendar: Calendar,
    check: Check,
    edit: Edit,
    plus: Plus,
    settings: Settings,
    phone: Phone,
    hospital: Hospital,
    smartwatch: Watch,
    medical: Stethoscope,
    bloodTest: Droplet,
    emergency: Activity,
    weight: Weight,
    shield: Shield,
    zap: Zap,
    badgeCheck: BadgeCheck,
    mail: Mail,
    message: MessageSquare,
    users: Users,
    database: Database,
    send: Send,
    star: Star,
    grid: Grid3x3,
    link: Link,
    unlink: Unlink,
    plug: Plug,
    appWindow: AppWindow,
    sparkles: Sparkles,
    lock: Lock,
    anonymize: CircleDashed,
    encryption: Key,
    control: Sliders,
    research: Microscope,
    publicHealth: ShieldCheck,
    trendingUp: TrendingUp,
    trendingDown: TrendingDown,
    trendingFlat: Minus,
    lineChart: LineChart,
    heartPulse: HeartPulse,
    briefcase: Briefcase,
    play: Play,
    arrowRight: ArrowRight,
    healthData: Activity,
    ecosystem: Network,
    environment: CloudSun,
    privacy: Lock,
    hospital2: Building2,
    clinic: Stethoscope,
    researchInst: Microscope,
    medicalDevice: HeartPulse,
    pharmacy: Pill,
    airQuality: Wind,
    pollen: Flower2,
    weather: Cloudy,
    dataVisualization: LineChart,
    quote: Quote,
    ai: BrainCircuit,
    heart: HeartPulse,
};